### ISSUE TITLE
I switched ASID of vCPU during a VMGEXIT, did vCPU go to the real-mode?

### ISSUE THREAD

**Issue by mincheolsung** [AMDESE/AMDSEV#125]
Hi,

I ran a SEV-ES VM with ASID 1, then switched it by setting vmcb->asid = 2 during a VMGEXIT (I know this is insane. This is just for fun!).
As I created a second VMSA with ASID2, VMRUN worked but I found there were nested page faults at 0xFFFFF000 and so on.
I am suspicious that the vCPU went to the real-mode when it had a new ASID. Is this possible?

**Comment by rrelph** [comment]
There are a few problems with this approach.

First, a VMRUN instruction using an ASID that hasn’t been “activated” using the ACTIVATE command should fail to execute at all. But you used an ASID that was already in use by a second guest, so you avoided that problem.
Assigning the ASID=1 guest’s VMCB with an ASID that is activated for a different guest, the memory contents of the ASID=1 guest will be jibberish since the encryption key for the 2 guests would be different. So… no surprise that you get random instruction execution with random exceptions. With SEV-ES the guest’s VMSA is also encrypted with the guest’s encryption key. So you’ll get random register values… random CR values, random PC, random segment registers, etc.

If you want to legitimately change the guest’s ASID, you can do that be using the DEACTIVATE command and then another ACTIVATE command with the new ASID.

Richard

**Comment by mincheolsung** [comment]
@rrelph Thanks for your comment. I activated ASID2 and loaded a new VMSA with initial register states (using LAUNCH_UPDATE_VMSA) while running a VM with ASID1. Then I switched vmcb->asid, vmcb->vmsa_pa during the VMGEXIT. In this way, I was able to VMRUN without any fault. But the random instruction was executed by the VMSA with the initial register states. I was wondering whether vCPU executed the completely random instructions or switched back to the real-mode and executed the processor initialization code due to the initial register states in the new VMSA.

**Comment by tlendacky** [comment]
The register state is loaded from the VMSA, so whatever state is represented in the new VMSA, is what would be switched to. If that is the "reset" state as Qemu/KVM establish when creating a VM, then all of the #NPFs at 0xFFFFF000 makes sense.

**Comment by mincheolsung** [comment]
@tlendacky If the new VMSA has the reset state, does vCPU switch back to the real-mode?
Can I use SEND_UPDATE_VMSA/RECEIVE_UPDATE_VMSA to make the new VMSA consistent with the old VMSA?

**Comment by tlendacky** [comment]
> @tlendacky If the new VMSA has the reset state, does vCPU switch back to the real mode? Can I use 
SEND_UPDATE_VMSA/RECEIVE_UPDATE_VMSA to make the new VMSA identical to the old VMSA?

Yes, the VMSA will cause the vCPU to switch to whatever state (as long as it is valid) is represented by the VMSA. The problem you will have is that whatever you point that new VMSA/ASID at is likely to fail since the memory contents were encrypted with ASID1 and when ASID2 tries to access the memory, it will appear as ciphertext because the keys are different.

**Comment by mincheolsung** [comment]
Is there any limitation if I copy the code and VMSA to be encrypted by ASID2 and let the vCPU (with ASID2) execute the copied code?

**Comment by rrelph** [comment]
What are you really trying to do here?

When it comes to SEV guests, you can’t do anything to them directly from the host side except mess them up. Using the SEV SEND/RECEIVE APIs you can ’send’ a VM from one machine to another (or to the same machine).

**Comment by mincheolsung** [comment]
@rrelph I am trying to switch the encryption key.
Wouldn't snapshotting the VM and then resuming it with a different ASID have the same effect as switching encryption keys?

**Comment by RARelph** [comment]
The only way to change/rotate the memory encryption key is to start a new guest and migrate the old guest to the new guest using the SEV SEND/RECEIVE APIs. The memory encryption key is established by the SEV LAUNCH_START or RECEIVE_START commands. If you use LAUNCH_START, the only way to put contents in the guest from the HV is using LAUNCH_UPDATE_DATA/VMSA (using unencrypted data.) If you use RECEIVE_START, the only way to put contents in the guest is using RECEIVE_UPDATE_DATA/VMSA (using data obtained from SEND_UPDATE_DATA/VMSA.) Anything else is going to produce trash.

**Comment by mincheolsung** [comment]
Thanks for the clarification!

Mincheol
