### ISSUE TITLE
Running workload off of initrd

### ISSUE THREAD

**Issue by rikonor** [AMDESE/AMDSEV#224]
Hello 👋 

I have been attempting to forego a full-fledged root filesystem and just run a workload off of initrd, with the reasoning being that it would be quite trivial to (1) reproducibly build an initramfs and (2) it would mean the workload itself is included in the measurement (as opposed to putting a rootfs hash in a kernel cmdline and letting dm-verity verify it).

Is this way of using SEV-SNP supported? I've done some work on this but the issues I run into are complicated enough that it doesn't seem like something that's appropriate to try to work through in the VirTEE matrix channel, hence my posting here.

**Comment by mdroth** [comment]
There are -kernel, -initrd, and -append options you can pass to launch-qemu.sh to directly boot kernel/initrd and pass them the associated cmdline options. This is supported and used heavily. If you are trying to alleviate the need for an root filesystem completely then that's more to do with how you are creating and setting up your initrd. I'd recommend getting that working as expected for a normal/non-SNP guest first. I'm not aware of anything special you'd need to do in this regard for SNP other than ensuring your guest kernel has SNP support.

As far as measurement, running with -kernel/-initrd does not mean the kernel/initrd will be measured, it will still mainly just be the OVMF guest firmware that gets measured. There are however builds of the OVMF guest firmware that support injecting the kernel/initrd hashes into firmware-reserved memory so that the hashes get measured along with firmware and the guest firmware itself will verify the kernel hashes when it actually loads the kernel/initrd into memory. But that's something to consider once you get past your initrd issues.

**Comment by dubek** [comment]
@rikonor Your idea is supported, as far as I know.

The OVMF build from this repo's snp-latest branch builds the `OvmfPkg/OvmfPkgX64.dsc` package type of OVMF, which does *not* measure kernel and initrd.

There's another OVMF package `OvmfPkg/AmdSevX64.dsc` which does have these measurements, coupled with QEMU to inject the relevant hashes (`kernel-hashes=on` argument). For example, in the confidential-containers projects they do exactly that -- put their agent inside initrd and boot it in a measured way (not sure it's already integrated with SNP, you'll have to ask there).

(I must say it's more than a year since I was actively working on this, so this might be old news.)

**Comment by its-luca** [comment]
Shameless self promotion: You might find some of the tooling and scripts from https://github.com/SNPGuard/snp-guard helpful

**Comment by rikonor** [comment]
@dubek @mdroth @its-luca Thank you all very much for the information. It's good to confirm it most likely is an issue with how we are creating our initramfs. I will reference kata-container and [snp-guard](https://github.com/SNPGuard/snp-guard) to see what they are doing differently.

**Comment by rikonor** [comment]
Just as a follow-up, I'd like to update that I'm now able to build SEV-SNP-capabale `initramfs`-based workloads. Referencing some of what's being done in `snp-guard` was very useful. Thanks again, all.
