### ISSUE TITLE
BUS error occurs when I try to access the BIOS memory, exit-code 0x404

### ISSUE THREAD

**Issue by Monxter-seu** [AMDESE/AMDSEV#255]
Hi, 
  I found that when I try to access the BIOS memory address (e.g. from 0xFE000 to 0xFFFFF) using devmem2 or busybox devmem in a SEV-SNP VM , the action triggered a SIGBUS signal. Then, the dmesg showed the following message:
[   30.056060] Wrong/unhandled opcode bytes: 0x8b, exit_code: 0x404, rIP: 0x577566600c3b
[   30.056743] SEV: Unsupported exit-code 0x404 in #VC exception (IP: 0x577566600c3b) 

  I looked into the kernel and found that it was triggered by:
  	if (!vc_raw_handle_exception(regs, error_code)) {
		/*
		 * Do not kill the machine if user-space triggered the
		 * exception. Send SIGBUS instead and let user-space deal with
		 * it.
		 */
		force_sig_fault(SIGBUS, BUS_OBJERR, (void __user *)0);
	}

  The BUG can be triggered in various situation, when program tries to access BIOS memory, it occurs.
  
  The environment of the host is kernel 6.11.4 with AMD 7763. The OS of guest is ubuntu 22.04LTS with kernel 6.10.10.
  I wonder whether it's a BUG or the mechanism of SEV-SNP do not allow users accessing the BIOS memory. 
  THX :)

ADD1.
 I thought the problem occurs when the program trie to access the shared memory from user space . But should the BIOS memory set as shared memory?

ADD2.
  I tried to look at the page table entry of the page table entry of the guest physical address 0xFE078(in 0xF0000 - 0xFFFFF) . The result shows as follows:
crash> ptov 0xfe078
VIRTUAL           PHYSICAL
ffff8b78c00fe078  fe078
crash> vtop ffff8b78c00fe078
VIRTUAL           PHYSICAL
ffff8b78c00fe078  fe078

PGD DIRECTORY: ffffffff87a3c000
PAGE DIRECTORY: 80000a1e01067
   PUD: a1e01f18 => 80000a1e02067
   PMD: a1e02000 => 80000a1e03067
   PTE: a1e037f0 => 80080000000fe163
  PAGE: fe000

      PTE         PHYSICAL  FLAGS
80080000000fe163    fe000   (PRESENT|RW|ACCESSED|DIRTY|GLOBAL|NX)

      PAGE       PHYSICAL      MAPPING       INDEX CNT FLAGS
ffffecbc40003f80    fe000                0        0  1 7ffffc0004000 reserved

  I found that C-bit is 1, that means the memory is encrpied , and it is a 'public' memory. I thouhght that should not happen that a 'public' memory is encrpied.

THX

**Comment by Monxter-seu** [comment]
After looking into the kernel code and Ovmf code ,I think that it's a bug caused by the memory management of Ovmf. We tried to pvalidate 0xFE078 address in the guest, and the 0x404 error do not occur again. So we think that the Ovmf wrongly marked the address as unaccepted, but the kernel set the C-bit as 1. I wondering whether it's a EDK2 bug or a kernel bug and where should I report it. THX.

**Comment by Monxter-seu** [comment]
After more experiment, we found that the 0xFE078 address is not a public address but a private address, which should not happen in SEV-SNP. Since we watched the address and found that the kernel didn't access the 0xFE078 address, we believe that it's the Ovmf that changes the property of the address and the Ovmf didn't pvalidate the 0xFE078 address after it changes the memory property from 'public' to 'private'. That may cause catastrophic result especially someone want to access that address in kernel mode.  The memory from 0xC0000 to 0xFFFFF have the problem.

**Comment by cai-fuqiang** [comment]
Hi~ The reporter and I are colleagues, and we are researching 
this issue together.  I would like to provide some additional 
details in the hope that they might capture your interest.

including:
* debugging details
* our current analysis
* our questions

## 1. debugging details

### 1.1 Debug/Test Program

1. Use the following simple bpftrace script to obtain VMM convert memory, map GPA
   to GMEM, or map GPA to user page.

   ```
   BEGIN {
           @global_pid=0
   }

   uprobe:/usr/bin/qemu-system-x86_64:main
   {
           @global_pid=pid;
   }

   uprobe:/usr/bin/qemu-system-x86_64:kvm_convert_memory
   /pid == @global_pid/
   {
           $start=arg0;
           $size=arg1;
           $end = $start+$size;
           if ($start < 0xfe078 && (arg0+arg1) > 0xfe078) {
                   printf("convert:%ld:PID(%d) comm(%s) start(%d) size(%d) private(%d)\n",
                           nsecs, pid, comm, $start, $size, arg2);
           }
   }

   // find gfn in gmemfd
   kprobe:kvm_gmem_get_pfn
   /pid == @global_pid/
   {
           $gfn = arg2;
           if ($gfn == 0xfe) {
                   printf("gmem_get:%ld:PID(%d) comm(%s) gfn(%lx) \n", nsecs, pid, comm, $gfn);
           }
   }

   // find gfn in userspace address space
   kprobe:__gfn_to_pfn_memslot
   /pid == @global_pid/
   {
           $gfn = arg1;
           if ($gfn == 0xfe) {
                   printf("memfd:%ld:PID(%d) comm(%s) gfn(%lx) \n", nsecs, pid, comm, $gfn);
           }
   }

   ```
2. kernel module: pvalidate xxxx
   ```
   func() {
      phys_addr_t start = 0xfe000;
      unsigned long vaddr = (unsigned long)pfn_to_kaddr(start >> 12);
      rc = pvalidate(vaddr, 0, SNP_PAGE_STATE_PRIVATE);
      return;
   }
   ```
3. userspace program: read xxxx phys_addr
   ```
   func() {
      int fd = open("/dev/mem", O_RDWR);
      void *ptr = mmap(NULL, 4096, PROT_READ, MAP_SHARED, fd, 0xfe000);
      void *other_ptr = ptr + 0x78;
      uint32_t value = *(uint32_t*)other_ptr;
   }
   ```
### 1.2 Test Steps && Debug Output

1. Before executing the kernel module and userspace program, there will be no
   output.
2. If only execute user space programs without executing kernel modules,
   it will trigger a #VE (Virtualization Exception).
   ```
   SEV: Unsupported exit-code 0x404 in #VC exception (IP: 0x40120a)
   ```
3. If the kernel module is executed first, and then execute user program,
   memory address (0xfe078) will be read normally.

2. No matter which test program is executed, bpftrace will print follow:
   ```
   gmem_get:1490730816502323:PID(942841) comm(qemu-system-x86) gfn(fe)
   ```

**Comment by cai-fuqiang** [comment]
## 2. our current analysis

So this indicates there was no access to the address 0xfe078 in the VM until
the test program was executed.

Because the pvalidate instruction also performs a nested page table walk,
it has never been executed after booting.

When KVM captures a #VMEXIT (NPF), it will use Bit 34 (ENC) in EXITINFO1
to decide whether to use gmem or user space page. As the reporter mentioned,
the kernel page table has a C bit, so KVM will look for the page in gmem.
However, the kernel did not pvalidate that address before accessing it,
so when KVM fixes the NPF and returns to the guest to re-execute the
instruction, it will directly trigger a #VC to the guest.

The kernel seems to only pvalidate memory that is EFI_UNACCEPTED_MEMORY
(either immediately or lazily). And when kernel build the e820 table
in efi-stub, it report this unaccepted memory as E820_TYPE_RAM. However,
when we checked the e820, we did not find that address space.

The following is the e820 in dmesg:

```
## no 0xfe pfn found
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000007fffff] usable
```

Additionally, if the address space is IO space, there doesn't seem to be an
issue, because the memory access instructions will trap to the VMM to emulate
and will set next ip when falling back to guest. However, that address space
is setting as RAM by QEMU.

The following is qemu mtree:
```
address-space: cpu-memory-0
address-space: memory
  0000000000000000-ffffffffffffffff (prio 0, i/o): system
    0000000000000000-000000007fffffff (prio 0, ram): alias ram-below-4g @pc.ram 0000000000000000-000000007fffffff
    0000000000000000-ffffffffffffffff (prio -1, i/o): pci
    00000000000ec000-00000000000effff (prio 1, i/o): alias pam-pci @pci 00000000000ec000-00000000000effff
    ## this range
    00000000000f0000-00000000000fffff (prio 1, i/o): alias pam-pci @pci 00000000000f0000-00000000000fffff
```

**Comment by cai-fuqiang** [comment]
## 3. questions

So, we would like to ask whether the kernel's behavior is correct
here: using a page table with the C bit to access memory not
reported by the BIOS.

Or if we have any misunderstandings, we hope you can help us correct
them.


THX

fuqiang

**Comment by mdroth** [comment]
There's more background discussion here:

  https://lore.kernel.org/lkml/20240216225019.upcxwd6vkxv5dp4n@amd.com/#t

but I think the high-level summary is that we do not want to allow these regions to be accessed without the C-bit set because that might allow for things like executable ROMs to be side-loaded into an SNP guest and compromise security.

Earlier SNP guest kernels avoided 0x404 errors on the kernel side by effectively PVALIDATE'ing that range prior to access by the kernel, but because userspace was, in all cases we are aware of, simply putting plain-text data in these regions (hence why the memory range wasn't pre-validated at boot-time via SNP_LAUNCH_UPDATE firmware command to begin with), the guest would end up reading ciphertext when accessing with the C-bit set, and this resulted in the kernel trying to interpret what was effectively garbage data.

So the current kernel code leaves C-bit set but skips accessing these regions to avoid triggering 0x404 exception:

  https://lore.kernel.org/lkml/20240222202404.36206-1-kevinloughlin@google.com/

so userspace should do the same as the kernel and not access those regions (unless it is a specialized case where userspace knows there is valid data in these regions, in which case it knows the VMM would have taken the appropriate steps to pre-PVALIDATE it before launch via SNP_LAUNCH_UPDATE and have those contents measured as part of the guest's overall attestated boot image.). Otherwise, I think the BUS_ERROR is appropriate behavior to avoid propagating garbage data/ciphertext further up the stack.

**Comment by Monxter-seu** [comment]
> There's more background discussion here:
> 
> https://lore.kernel.org/lkml/20240216225019.upcxwd6vkxv5dp4n@amd.com/#t
> 
> but I think the high-level summary is that we do not want to allow these regions to be accessed without the C-bit set because that might allow for things like executable ROMs to be side-loaded into an SNP guest and compromise security.
> 
> Earlier SNP guest kernels avoided 0x404 errors on the kernel side by effectively PVALIDATE'ing that range prior to access by the kernel, but because userspace was, in all cases we are aware of, simply putting plain-text data in these regions (hence why the memory range wasn't pre-validated at boot-time via SNP_LAUNCH_UPDATE firmware command to begin with), the guest would end up reading ciphertext when accessing with the C-bit set, and this resulted in the kernel trying to interpret what was effectively garbage data.
> 
> So the current kernel code leaves C-bit set but skips accessing these regions to avoid triggering 0x404 exception:
> 
> https://lore.kernel.org/lkml/20240222202404.36206-1-kevinloughlin@google.com/
> 
> so userspace should do the same as the kernel and not access those regions (unless it is a specialized case where userspace knows there is valid data in these regions, in which case it knows the VMM would have taken the appropriate steps to pre-PVALIDATE it before launch via SNP_LAUNCH_UPDATE and have those contents measured as part of the guest's overall attestated boot image.). Otherwise, I think the BUS_ERROR is appropriate behavior to avoid propagating garbage data/ciphertext further up the stack.

Thank you for you answering, we think it is quite an appropriate way to handle that memory region. :)
