### ISSUE TITLE
Is guest SMM required for SEV guest firmware

### ISSUE THREAD

**Issue by pgonda** [AMDESE/AMDSEV#26]
https://github.com/AMDESE/AMDSEV/blob/7fd01aedb3cf68115f5409aa76fa89a1cc442103/distros/common.sh#L68

When building OVMF the -DSMM_REQUIRED flag is added, this causes a [assertion failure if SMM is not emulated.](http://go/gh/tianocore/edk2/blob/master/OvmfPkg/README#L135) Though reading through the SEV support in OVMF it seems like this is [optional](http://go/gh/tianocore/edk2/blob/master/OvmfPkg/AmdSevDxe/AmdSevDxe.c#L75). 

Is this flag needed or can it be removed?

**Comment by codomania** [comment]
SMM is not must for the SEV guest itself. If the HV does not emulate the SMM then feel free to disable it. OVMF recommends SMM for the secure boot so that you can have a boot that is actually secure. I believe some distro's like RHEL or Suse provides prebuilt OVMF binaries with Secure Boot plus SMM enabled by default. So in the build script, I tried to ensure that SEV works fine with Secure Boot plus SMM combination.

**Comment by pgonda** [comment]
Thanks for the explanation. Closing.
