### ISSUE TITLE
Can not find ubuntu-18.04-desktop-amd64.iso

### ISSUE THREAD

**Issue by CodingYuanLiu** [AMDESE/AMDSEV#60]
Hello, 
I want to run SEV on ubuntu-18.10 machine, so I follow the guide of ubuntu-18.04 and finish the operations in `./build.sh` with no error.
However, when running: 
``` bash
# launch-qemu.sh -hda ubuntu-18.04.qcow2 -cdrom ubuntu-18.04-desktop-amd64.iso
```
I can not find `ubuntu-18.04-desktop-amd64.iso`. I had thought that it will be generated by `./build.sh`
How can I find this iso file? 

By the way, I have installed ubuntu-18.04.5-desktop-amd64.iso from ubuntu's website and try to replace ubuntu-18.04-desktop-amd64.iso, but obviously, the guest VM can not start up and stuck in the UEFI:

My command:
```bash
launch-qemu.sh -hda ubuntu-18.04.qcow2 -cdrom ubuntu-18.04.5-desktop-amd64.iso -console serial
```
Part of the outputs:
```bash
......
ConvertPages: range 1000000 - 3B6BFFF covers multiple entries                                                      
ConvertPages: range 1000000 - 3B6BFFF covers multiple entries                                                       
SmmInstallProtocolInterface: 296EB418-C4C8-4E05-AB59-39E8AF56F00A 0                                                 
MpInitChangeApLoopCallback() done!                                                                                  
SetUefiImageMemoryAttributes - 0x000000007EBC4000 - 0x0000000000006000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EBBE000 - 0x0000000000006000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EBB8000 - 0x0000000000006000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EBB2000 - 0x0000000000006000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EBAB000 - 0x0000000000007000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EBA2000 - 0x0000000000009000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007EB9A000 - 0x0000000000008000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007DAE1000 - 0x0000000000007000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007DA90000 - 0x0000000000005000 (0x0000000000000008)                         
SetUefiImageMemoryAttributes - 0x000000007DA86000 - 0x0000000000005000 (0x0000000000000008)   
```
Thank you in advance.

**Comment by tlendacky** [comment]
You have to download your own ISO of the Ubuntu distribution, the script does not do that for you.

Follow the instructions in the README file. To install the guest use the -vnc 1 argument on the launch-qemu.sh command line. Then use a vnc client to access the GUI environment and perform the install.

**Comment by tlendacky** [comment]
Just tried it here with that particular ISO and didn't have any issues. Not sure what might be wrong.

**Comment by CodingYuanLiu** [comment]
I restart the VM and it now can work (It needs multiple restarts. Quite mysterious). 

Can I use terminal instead of GUI to access the VM? Directly call:
``` bash
launch-qemu.sh -hda ubuntu-18.04.qcow2 -cdrom ubuntu-18.04.5-desktop-amd64.iso
```
will cause `gtk initialization failed`

Simply add `-console serial` to launch_qemu.sh parameters will stuck in the UEFI, as I mentioned before.

By the way, why can we use a self-downloaded ubuntu iso file, whose kernel (kernel of the guest VM) may not support SEV? What have we done in `build_kernel` and `install_kernel` in `build.sh`?
Thank you in advance

**Comment by tlendacky** [comment]
You can use the terminal instead of the GUI if you can catch the grub menu in the VNC session quick enough. You would need to edit the kernel command line parameters to add a serial console (console=tty0 console=ttyS0,115200n8). Once installed, you can edit /etc/default/grub to add the serial console to GRUB_CMDLINE_LINUX_DEFAULT and get grub to display on the serial console using:
  GRUB_TERMINAL_INPUT="serial console"
  GRUB_TERMINAL_OUTPUT="serial console"
  GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"

Without the serial console for grub or the kernel then, yes, it appears stuck in UEFI, but it actually isn't (which is why when you added the -vnc option you were able to connect to the installation).

The SEV-ES guest kernel support was only just added to the 5.10 kernel. Therefore, until a distro picks up that kernel, you need to install without SEV-ES. The build.sh script builds a kernel that you then install in the guest so that you run as an SEV-ES guest.

**Comment by CodingYuanLiu** [comment]
It works now. Thank you very much for your help.
