### ISSUE TITLE
qemu VM reboot

### ISSUE THREAD

**Issue by churkanerusskaya** [AMDESE/AMDSEV#61]
Hello! 
Is it possible to reboot the sev-es enabled qemu VM? When I try to do this, the VM always goes into "shut off"  state, so I need to turn it on manually every time. 
And a little question - how will SEV-ES work in multiprocessor systems? The HOST OS scheduler can transfer VMs between different physical CPU for a load balancing purposes, but each CPU has its own set of keys. Does this mean that it's required to bind  VM it's to particular physical CPU?

Thank you!

**Comment by tlendacky** [comment]
A reboot is not possible with Qemu as it is today. A reboot under Qemu is accomplished by resetting the processor state. Since this state is already measured, that would result in an error when trying run the vCPU. To properly accomplish a restart, the VM must go through the launch process again, which is not easy under Qemu as it exists today. Therefore, the guest shuts down and must be re-started.

There is no issue in multiprocessor systems. The vCPU is free to move between host CPUs and the hardware ensures the proper key is present to run the vCPU on the physical CPU.

**Comment by churkanerusskaya** [comment]
Thanks
